version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: base-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup         
    networks:
      - backend-net

volumes:
  postgres_data: {}            

networks:
  backend-net:
    name: backend-net            
